{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: gcr.io/daniels-tools/webapp:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
{{- end }}