{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
spec:
  type: NodePort 
  selector:
    app: nginx-proxy
  ports:
    - port: 30500
      targetPort: 80
      nodePort: 30500  
{{- end }}  