{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: person-service
spec:
  selector:
    app: person-service
  ports:
    - port: 8080
      targetPort: 8080
  # todo ClusterIP    
  type: LoadBalancer 
{{- end }}  