apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "daniels-tools-kube-service-static-ip"
spec:
  rules:
  - http:
      paths:
      {{- if index .Values "nginx-proxy" "enabled" }}
      - path: /*
        backend:
          serviceName: nginx-proxy
          servicePort: 30500
      {{- end }}

