{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: gcr.io/daniels-tools/counter-service:latest
          ports:
            - containerPort: 5000
          # todo
          env: 
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          imagePullPolicy: Always
{{- end }}
