{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter-service
  ports:
    - port: 5000
      targetPort: 5000
  # todo ClusterIP    
  type: LoadBalancer 
{{- end }}  